endpoints:
  health: 
    Lenabled : true

server:
  port: 8087

logging:
  level:
    com:
      greglturnquist: DEBUG
    org:
      springframework:
        data: TRACE
    reactor:
      core: TRACE
      util: TRACE

spring:
  devtools:
    restart: 
      enabled: true
